# site settings
title: FGHTech
subtitle: by Sweden
email: Shoot me a message through the form on your left!
description: Digital services, Web development,<br /> and Tech Startups.
permalink: 
baseurl:  # the subpath of your site, e.g. /blog
url: fghtech.com # the base hostname & protocol for your site
author:
street_address: Runborgsvägen 8
city: Täby
state: 
zip_code: 18772
country: Sweden
phone: +46 76 402 66 44

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
