# site settings
title: FGHTech
subtitle: by Sweden
email: 
description: Digital services, Web development,<br /> and Tech Startups.
permalink: 
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: 
street_address: FGHTech AB
city: Krossbacken 8
state: Täby
zip_code: 18770
country: Sweden
#phone: +46 76 402 66 44

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
link_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
